name: common_locale_data
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  build_runner:
  dart_style:
  http:
  json_annotation:
  json_serializable:
  lints:
  process_runner:
  test:
